In [ ]:
import numpy as np

In [ ]:
# scalar

s = 5


In [ ]:
s 

#5

In [ ]:
# Vector

v = np.array([5, 3, -1])

In [ ]:
v

# array([ 5,  3, -1])

In [ ]:
# matrices

m = np.array([[5, 3, -1], [0, 1,3]])
m

# array([[ 5,  3, -1],
#    [ 0,  1,  3]])

In [ ]:
# Data Types

type(s) 

# int

In [ ]:
type(v) 


# numpy.ndarray => n dimensional array

In [ ]:
type(m)

# numpy.ndarray => n dimensional array

In [ ]:
s =  np.array(5)
s

In [ ]:
type(s)

# numpy.ndarray

In [ ]:
# Data shapes
m.shape 

# (2,3)

In [ ]:
v.shape 

# (3,)

In [ ]:
# Creating column vector

v.reshape(1,3) 

# array([[ 5,  3, -1]])

In [ ]:
v.reshape(3, 1)

# array([[ 5],
       [ 3],
       [-1]])


In [ ]:
s.shape

# () => no shape as it is a scalar
