In [ ]:
import numpy as np

In [ ]:
m1 = np.array([[5,1,9], [2,8,1]])
m1

#array([[5, 1, 9],
#      [2, 8, 1]])

In [ ]:
m2 = np.array([[5,1,6], [7,4,1]])
m2

# array([[5, 1, 6],
#      [7, 4, 1]])

In [ ]:
m3 = np.array([m1, m2])
m3

#array([[[5, 1, 9],
#        [2, 8, 1]],

#       [[5, 1, 6],
#        [7, 4, 1]]])

In [ ]:
# Data shape

m3.shape

# (2,2,3) => 2 matrices each with 2 rows and 3 columns